# Generated by Django 4.2.5 on 2023-10-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='mobno',
            field=models.CharField(max_length=50),
        ),
    ]
