# Generated by Django 4.2.5 on 2023-10-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_alter_table1_mobno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table1',
            name='name',
        ),
    ]
