# Generated by Django 4.2.5 on 2023-10-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_remove_table1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
