# Generated by Django 4.2.5 on 2023-10-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_table1_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table1',
            new_name='table',
        ),
    ]
