# Generated by Django 4.2.5 on 2023-10-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_rename_table1_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='table2',
        ),
    ]
